version: "2"

services:
# this 'entrypoint' service will need to be re-done to refer to the new noteoj_web thing
  entrypoint:
    build: entrypoint
    ports:
      - 80:80
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  db:
    image: postgres:9.4
